## A pair of functions that enable the inverse of a matrix to be computed and cached.
## If the matrix remains unchanged the inverse of the matrix is retrived from cache,
## otherwise it is recomputed.


## Create a 'matrix' object that can store a matrix and its inverse.
## Can take an optional matrix as input, otherwise defaults to an empty matrix.
## Returns a list of functions to access the matrix and its inverse.

makeCacheMatrix <- function(x = matrix()) {
    inverse <- NULL
    
    ## Store a new matrix and clear the currently stored inverse matrix
    set <- function(newMatrix) {
        x <<- newMatrix
        inverse <<- NULL
    }
    
    ## Retrieve the currently stored matrix
    get <- function() x
    
    ## Store an inverse matrix
    setinverse <- function(inv) inverse <<- inv
    
    ## Retrieve the currently stored inverse matrix
    getinverse <- function() inverse
    
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}

## Calculate the inverse of a matrix. If the inverse has already been calculated
## retrieve it from cache.
## Takes as input a 'matrix' object generated by makeCacheMatrix.
## Returns the inverse of the matrix.

cacheSolve <- function(x, ...) {
    inverse <- x$getinverse()
    if (!is.null(inverse)) {
        message("Getting cached data...")
        return(inverse)
    }
    matrix <- x$get()
    inverse <- solve(matrix)
    x$setinverse(inverse)
    inverse
}
